version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    expose:
      - "3000"
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    volumes:
      - "./services/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    depends_on:
      - app