version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    volumes:
      - "./services/nginx/defult.conf:/etc/nginx/conf.d/defult.conf"
    ports:
      - "8080:3000"
    depends_on:
      - app