---

- hosts: all
  gather_facts: false
  vars:
    ansible_connection: local
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - template:
        src: secrets.auto.tfvars.j2
        dest: '../terraform/secrets.auto.tfvars'